In [1]:
import os
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import classification_report, confusion_matrix

# Directory containing frames for each dataset
train_dir = r"C:\Users\Shree\Downloads\IITB\frames_Test"
val_dir = r"C:\Users\Shree\Downloads\IITB\frames_Train"
test_dir = r"C:\Users\Shree\Downloads\IITB\frames_validation"

# Parameters
img_height, img_width = 128, 128  # Image dimensions
batch_size = 32
epochs = 25  # Number of epochs
steps_per_epoch = 150  # Fixed number of steps per epoch
validation_steps = 150  # Fixed number of validation steps

# Create an ImageDataGenerator for data augmentation and normalization
datagen = ImageDataGenerator(rescale=1.0/255.0)

# Load training data
train_generator = datagen.flow_from_directory(
    train_dir,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode='categorical'
)

# Load validation data
val_generator = datagen.flow_from_directory(
    val_dir,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode='categorical'
)

# Load test data
test_generator = datagen.flow_from_directory(
    test_dir,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode='categorical',
    shuffle=False  # Ensure the order is maintained for evaluation
)

# Determine the number of classes
num_classes = train_generator.num_classes
print(f'Number of classes: {num_classes}')

# Define the CNN model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(img_height, img_width, 3)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(150, activation='relu'),  # Updated dense layer to 150 units
    Dropout(0.5),
    Dense(num_classes, activation='softmax')  # Output layer with number of classes
])

# Compile the model
model.compile(optimizer=Adam(),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
history = model.fit(
    train_generator,
    steps_per_epoch=steps_per_epoch,  # Fixed number of steps per epoch
    validation_data=val_generator,
    validation_steps=validation_steps,  # Fixed number of validation steps
    epochs=epochs  # Number of epochs
)

# Save the model
model.save('emotion_classification_model.h5')

# Evaluate the model on test data
print("Evaluating the model on test data...")
test_loss, test_accuracy = model.evaluate(test_generator)
print(f'Test Loss: {test_loss}')
print(f'Test Accuracy: {test_accuracy}')

# Get predictions on test data
Y_pred = model.predict(test_generator)
y_pred = np.argmax(Y_pred, axis=1)
y_true = test_generator.classes

# Print classification report and confusion matrix
print('Classification Report')
print(classification_report(y_true, y_pred, target_names=test_generator.class_indices.keys()))

print('Confusion Matrix')
print(confusion_matrix(y_true, y_pred))

print("Model trained, evaluated on test data, and saved successfully as 'emotion_classification_model.h5'.")


Found 17986 images belonging to 4 classes.
Found 18660 images belonging to 4 classes.
Found 14290 images belonging to 4 classes.
Number of classes: 4


Epoch 1/25


150/150 [==============================] - 129s 839ms/step - loss: 0.6912 - accuracy: 0.7644 - val_loss: 0.7253 - val_accuracy: 0.7542
Epoch 2/25
150/150 [==============================] - 98s 657ms/step - loss: 0.6370 - accuracy: 0.7656 - val_loss: 0.7631 - val_accuracy: 0.7423
Epoch 3/25
150/150 [==============================] - 83s 557ms/step - loss: 0.5812 - accuracy: 0.7823 - val_loss: 0.7943 - val_accuracy: 0.7496
Epoch 4/25
150/150 [==============================] - 74s 497ms/step - loss: 0.5700 - accuracy: 0.7796 - val_loss: 0.7818 - val_accuracy: 0.7440
Epoch 5/25
150/150 [==============================] - 67s 444ms/step - loss: 0.5547 - accuracy: 0.7790 - val_loss: 0.8529 - val_accuracy: 0.7454
Epoch 6/25
150/150 [==============================] - 61s 409ms/step - loss: 0.5316 - accuracy: 0.7908 - val_loss: 0.88

C:\Users\Shree\anaconda3\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


447/447 [==============================] - 162s 362ms/step - loss: 2.2994 - accuracy: 0.5257
Test Loss: 2.2993578910827637
Test Accuracy: 0.525682270526886
447/447 [==============================] - 42s 94ms/step
Classification Report
              precision    recall  f1-score   support

     Boredom       0.13      0.02      0.04      1630
   Confusion       0.00      0.00      0.00       110
  Engagement       0.57      0.84      0.68      8140
 Frustration       0.30      0.14      0.19      4410

    accuracy                           0.53     14290
   macro avg       0.25      0.25      0.23     14290
weighted avg       0.43      0.53      0.45     14290

Confusion Matrix
[[  38    0 1266  326]
 [   0    0  100   10]
 [ 180    0 6860 1100]
 [  73    0 3723  614]]
Model trained, evaluated on test data, and saved successfully as 'emotion_classification_model.h5'.


C:\Users\Shree\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Shree\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Shree\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)